version: '3.7'

services:
  faceapi:
    image: "akbarnotopb/face-api"
    container_name: "face-recog-api"
    ports:
      - 8080:8080
    volumes:
      - ./src:/app
    environment:
      GUNICORN_WORKER: 2
      GUNICORN_PORT: 8080
  